CREATE PROCEDURE [dbo].[FI_SP_DelCliente]
    @Id BIGINT
AS
BEGIN
    SET NOCOUNT ON;  

     DELETE FROM BENEFICIARIOS 
     WHERE IDCLIENTE = @Id
     
     DELETE FROM CLIENTES 
     WHERE ID = @Id

END